set EPICS_HOST_ARCH=win32-x86
set EPICS_BASE=C:\EPICS\base\
set EPICS_TOP=%EPICS_BASE%
set EPICS_BIN=%EPICS_BASE%\bin\%EPICS_HOST_ARCH%
set EPICS_CA_ADDR_LIST=127.0.0.1
set EPICS_CA_AUTO_ADDR_LIST=NO
set PATH=%EPICS_BIN%;%PATH%

set EPICSQT=C:\EPICS_SVN\EPICS\trunk\ISIS\EPICS_Qt_Framework\epicsqt\
set QCAQTDIR=C:\QtSDK\
set QCAFRAMEWORK=%EPICSQT%\ca_framework
set PATH=%QCAQTDIR%\Desktop\Qt\4.8.1\msvc2010\bin;%PATH%
set PATH=%QCAQTDIR%\QtCreator\bin;%PATH%

