# This file was automatically generated on Tue 19 Oct 2010 09:59:53 BST from
# source: /dls_sw/prod/R3.14.11/support/eurotherm2k/1-11/etc/makeIocs/example.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
< envPaths

cd "$(INSTALL)"

epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(INSTALL)"

dbLoadDatabase "dbd/example.dbd"
example_registerRecordDeviceDriver(pdbbase)

#drvAsynIPPortConfigure("eurothermAsyn", "172.23.111.180:7001", 100, 0, 0)
drvAsynSerialPortConfigure("eurothermAsyn","\\.\COM5",0,0,0)
asynSetOption("eurothermAsyn", 0, "baud", "9600")
asynSetOption("eurothermAsyn", 0, "bits", "7")
asynSetOption("eurothermAsyn", 0, "parity", "even")
asynSetOption("eurothermAsyn", 0, "stop", "1")
asynSetOption("eurothermAsyn", 0, "clocal", "Y")
asynSetOption("eurothermAsyn", 0, "crtscts", "N")

# Configure StreamDevice paths
epicsEnvSet "STREAM_PROTOCOL_PATH", "$(EUROTHERM2K)/eurotherm2kApp/protocol"

#var streamDebug 1

# Final ioc initialisation
# ------------------------
cd "$(INSTALL)"
dbLoadRecords 'db/example_expanded.db'
iocInit
