#!/bin/sh
# This file was automatically generated on Tue 19 Oct 2010 09:59:54 BST from
# source: /dls_sw/prod/R3.14.11/support/eurotherm2k/1-11/etc/makeIocs/example.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
#    export HOME_DIR="$(cd "$(dirname "$0")"/../..; pwd)"
# cd "$HOME_DIR"
./example stexample.boot
