# This file was automatically generated on Tue 19 Oct 2010 09:59:54 BST from
# source: /dls_sw/prod/R3.14.11/support/eurotherm2k/1-11/etc/makeIocs/example.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(INSTALL)"

epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(INSTALL)"

dbLoadDatabase "dbd/example.dbd"
example_registerRecordDeviceDriver(pdbbase)

drvAsynIPPortConfigure("eurothermAsyn", "localhost:8101", 100, 0, 0)

# Configure StreamDevice paths
epicsEnvSet "STREAM_PROTOCOL_PATH", "$(EUROTHERM2K)/data"

# Final ioc initialisation
# ------------------------
cd "$(INSTALL)"
dbLoadRecords 'db/example_expanded.db'
iocInit
